CREATE  TABLE `languages` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `code` VARCHAR(2) NOT NULL ,
  `name` VARCHAR(50) NOT NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `code` (`code` ASC)
);


INSERT INTO `languages` VALUES
('aa', 'Afar, Hamitisch'),
('ab', 'Abchazisch'),
('ae', 'Avestisch'),
('af', 'Afrikaans'),
('ak', 'Akan'),
('am', 'Amhaars, Amharisch'),
('an', 'Aragonees'),
('ar', 'Arabisch'),
('as', 'Assamees, Assami'),
('av', 'Avaars'),
('ay', 'Aymara, Aymará'),
('az', 'Azerbeidzjaans, Azeri'),
('ba', 'Basjkiers, Basjkirisch'),
('be', 'Wit-Russisch, Belarussisch'),
('bg', 'Bulgaars'),
('bh', 'Bihari'),
('bi', 'Bislama'),
('bm', 'Bambara'),
('bn', 'Bengaals'),
('bo', 'Tibetaans'),
('br', 'Bretons'),
('bs', 'Bosnisch'),
('ca', 'Catalaans'),
('ce', 'Tsjetsjeens'),
('ch', 'Chamorro'),
('co', 'Corsicaans'),
('cr', 'Cree'),
('cs', 'Tsjechisch'),
('cu', 'Kerkslavisch'),
('cv', 'Tsjoevasjisch'),
('cy', 'Welsh'),
('da', 'Deens'),
('de', 'Duits'),
('dv', 'Divehi'),
('dz', 'Dzongkha'),
('ee', 'Ewe'),
('el', 'Grieks'),
('en', 'Engels'),
('eo', 'Esperanto'),
('es', 'Spaans'),
('et', 'Estisch, Ests'),
('eu', 'Baskisch'),
('fa', 'Perzisch, Farsi'),
('ff', 'Fula'),
('fi', 'Fins'),
('fj', 'Fijisch'),
('fo', 'Faeröers'),
('fr', 'Frans'),
('fy', 'Fries'),
('ga', 'Iers-Gaelisch'),
('gd', 'Schots-Gaelisch'),
('gl', 'Galicisch'),
('gn', 'Guaraní'),
('gu', 'Gujarati'),
('gv', 'Manx-Gaelisch'),
('ha', 'Hausa'),
('he', 'Hebreeuws'),
('hi', 'Hindi'),
('ho', 'Hiri Motu'),
('hr', 'Kroatisch'),
('ht', 'Kreyòl'),
('hu', 'Hongaars'),
('hy', 'Armeens'),
('hz', 'Herero'),
('ia', 'Interlingua'),
('id', 'Indonesisch'),
('ie', 'Interlingue'),
('ig', 'Igbo'),
('ii', 'Yi'),
('ik', 'Inupiak'),
('io', 'Ido'),
('is', 'IJslands'),
('it', 'Italiaans'),
('iu', 'Inuktitut'),
('ja', 'Japans'),
('jv', 'Javaans'),
('ka', 'Georgisch'),
('kg', 'Kikongo'),
('ki', 'Gikuyu'),
('kj', 'Kwanyama'),
('kk', 'Kazachs'),
('kl', 'Groenlands'),
('km', 'Khmer, Cambodjaans'),
('kn', 'Kannada, Kanarees, Kanara'),
('ko', 'Koreaans'),
('kr', 'Kanuri'),
('ks', 'Kasjmiri, Kasjmiers, Kasjmirs'),
('ku', 'Koerdisch'),
('kv', 'Zurjeens'),
('kw', 'Cornisch'),
('ky', 'Kirgizisch'),
('la', 'Latijn'),
('lb', 'Luxemburgs'),
('lg', 'Luganda'),
('li', 'Limburgs'),
('ln', 'Lingala'),
('lo', 'Laotiaans'),
('lt', 'Litouws'),
('lu', 'Luba-Katanga'),
('lv', 'Lets'),
('mg', 'Plateaumalagasi'),
('mh', 'Marshallees'),
('mi', 'Maori'),
('mk / sl', 'Macedonisch'),
('ml', 'Malayalam'),
('mn', 'Mongools'),
('mo', 'Moldavisch'),
('mr', 'Marathi'),
('ms', 'Maleis'),
('mt', 'Maltees'),
('my', 'Birmaans, Birmees'),
('na', 'Nauruaans'),
('nb', 'Norwegian Bokmål'),
('nd', 'Noord-Ndebele'),
('ne', 'Nepalees, Nepali'),
('ng', 'Ndonga'),
('nl', 'Nederlands'),
('nn', 'Nynorsk'),
('no', 'Noors'),
('nr', 'Zuid-Ndebele'),
('nv', 'Navajo'),
('ny', 'Nyanja'),
('oc', 'Occitaans'),
('oj', 'Ojibweg'),
('om', 'Afaan Oromo'),
('or', 'Oriya'),
('os', 'Ossetisch'),
('pa', 'Punjabi'),
('pi', 'Pali'),
('pl', 'Pools'),
('ps', 'Pasjtoe, Pasjto, Pashtoe'),
('pt', 'Portugees'),
('qu', 'Quechua'),
('rm', 'Reto-Romaans'),
('rn', 'Kirundi'),
('ro', 'Roemeens'),
('ru', 'Russisch'),
('rw', 'Kinyarwanda'),
('sa', 'Sanskriet'),
('sc', 'Sardijns'),
('sd', 'Sindhi'),
('se', 'Noord-Samisch, Noord-Laps'),
('sg', 'Sangho'),
('sh', 'Servo-Kroatisch'),
('si', 'Singalees'),
('sk', 'Slowaaks'),
('sl', 'Sloveens'),
('sm', 'Samoaans'),
('sn', 'Shona'),
('so', 'Somalisch'),
('sq', 'Albanees'),
('sr', 'Servisch'),
('ss', 'Swazi'),
('st', 'Zuid-Sotho'),
('su', 'Soendanees, Sundanees'),
('sv', 'Zweeds'),
('sw', 'Swahili'),
('ta', 'Tamil'),
('te', 'Telugu, Teloegoe'),
('tg', 'Tadzjieks'),
('th', 'Thai, Thais'),
('ti', 'Tigrinya'),
('tk', 'Turkmeens, Toerkmeens'),
('tl', 'Tagalog'),
('tn', 'Tswana'),
('to', 'Tongaans, Tonga'),
('tr', 'Turks'),
('ts', 'Tsonga'),
('tt', 'Tataars, Tartaars'),
('tw', 'Twi'),
('ty', 'Tahitiaans'),
('ug', 'Oeigoers'),
('uk', 'Oekraïens'),
('ur', 'Urdu'),
('uz', 'Oezbeeks'),
('ve', 'Venda'),
('vi', 'Vietnamees'),
('vo', 'Volapük, Volapuk'),
('wa', 'Waals'),
('wo', 'Wolof'),
('xh', 'Xhosa'),
('yi', 'Jiddisch'),
('yo', 'Yoruba'),
('za', 'Zhuang, Tsjoeang'),
('zh', 'Chinees'),
('zu', 'Zoeloe');
